### ISSUE TITLE
Documents needed

### ISSUE THREAD

**Issue by cbahlai** [BahlaiLab/Policies#2]
- [x] Safety/emergency info
- [x] lab roster
- [x] data management expectations
- [x] code management expectations
- [ ] Chemicals list with links to MSDS sheets
- [ ] fieldwork policies

**Comment by cbahlai** [comment]
@JuliaPerrone just going back through this- do you have those safety docs we could add here? even make it an activity for lab meeting to refresh everyone on uploading files

**Comment by JuliaPerrone** [comment]
Yes! That's a good plan!

*Julia Perrone*

*She/Her*

*Bahlai Lab Manager*
*Kent State University*
*Department of Biological Sciences*
*249 Cunningham Hall*
*(269) 806-1467*

*bahlailab.org <http://bahlailab.org>*
